name: Append new data to bird_records data source

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
      - cron: "0 1 * * *"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run ingestion.py
        env:
          TB_TOKEN: ${{ secrets.TB_TOKEN }}
        run: python scripts/ingestion.py